from pathlib import Path

p = Path('app/src/main/java/ro/auracamera/app/AuraActivity.java')
s = p.read_text(encoding='utf-8')

old = '    private Image pendingRaw; private TotalCaptureResult pendingRawResult;\n'
new = old + '''    // AURA MAX Stage 1: bracketed multi-frame capture + best-frame + local computational fusion.\n    private final List<Bitmap> burstFrames=new ArrayList<>();\n    private int burstExpected=0; private boolean burstNight=false,burstActive=false;\n    private long burstStarted=0; private int liveAuraScore=0;\n'''
if old not in s:
    raise SystemExit('field anchor not found')
s = s.replace(old,new,1)

s = s.replace('jpegReader=ImageReader.newInstance(js.getWidth(),js.getHeight(),ImageFormat.JPEG,2);',
              'jpegReader=ImageReader.newInstance(js.getWidth(),js.getHeight(),ImageFormat.JPEG,8);',1)

old_take = '''    private void takePhoto(){if(camera==null||session==null)return;if(motion>3.2f){guideText.setText("Ține telefonul stabil…");new Handler(getMainLooper()).postDelayed(this::takePhoto,180);return;}try{CaptureRequest.Builder b=camera.createCaptureRequest(CameraDevice.TEMPLATE_STILL_CAPTURE);b.addTarget(jpegReader.getSurface());if(rawEnabled&&rawReader!=null)b.addTarget(rawReader.getSurface());applyQuality(b,true);b.set(CaptureRequest.JPEG_ORIENTATION,0);session.capture(b.build(),new CameraCaptureSession.CaptureCallback(){@Override public void onCaptureCompleted(CameraCaptureSession s,CaptureRequest r,TotalCaptureResult res){synchronized(AuraActivity.this){pendingRawResult=res;trySaveRaw();}updatePreview();}},bg);}catch(Exception e){toast("Fotografie: "+e.getMessage());}}\n'''
new_take = '''    private void takePhoto(){\n        if(camera==null||session==null||burstActive)return;\n        if(motion>3.2f){guideText.setText("Ține telefonul stabil…");new Handler(getMainLooper()).postDelayed(this::takePhoto,180);return;}\n        try{\n            boolean night=mode.equals("Noapte")||scene.equals("NOAPTE");\n            int[] bracket=night?new int[]{-1,0,0,1,1}:new int[]{-2,-1,0,1,2};\n            List<CaptureRequest> requests=new ArrayList<>();\n            synchronized(burstFrames){for(Bitmap x:burstFrames)if(x!=null&&!x.isRecycled())x.recycle();burstFrames.clear();}\n            burstExpected=bracket.length;burstNight=night;burstActive=true;burstStarted=System.currentTimeMillis();\n            for(int ev:bracket){\n                CaptureRequest.Builder b=camera.createCaptureRequest(CameraDevice.TEMPLATE_STILL_CAPTURE);\n                b.addTarget(jpegReader.getSurface());applyQuality(b,true);\n                b.set(CaptureRequest.CONTROL_AE_EXPOSURE_COMPENSATION,clampEv(autoEv+ev));\n                b.set(CaptureRequest.JPEG_ORIENTATION,0);requests.add(b.build());\n            }\n            guideText.setText(night?"AURA NIGHT · combin cadre…":"AURA HDR · combin cadre…");\n            session.captureBurst(requests,new CameraCaptureSession.CaptureCallback(){\n                @Override public void onCaptureSequenceCompleted(CameraCaptureSession ss,int sequenceId,long frameNumber){updatePreview();}\n                @Override public void onCaptureSequenceAborted(CameraCaptureSession ss,int sequenceId){burstActive=false;updatePreview();}\n            },bg);\n        }catch(Exception e){burstActive=false;toast("Fotografie: "+e.getMessage());}\n    }\n'''
if old_take not in s:
    raise SystemExit('takePhoto anchor not found')
s=s.replace(old_take,new_take,1)

old_proc = '''    private void processJpeg(Image image){try{ByteBuffer bb=image.getPlanes()[0].getBuffer();byte[] data=new byte[bb.remaining()];bb.get(data);Bitmap dec=BitmapFactory.decodeByteArray(data,0,data.length);if(dec==null)throw new Exception("JPEG invalid");Bitmap oriented=orient(dec);Bitmap aura=applyLook(oriented);if(saveOriginal)saveBitmap(oriented,"AURA_ORIGINAL_"+System.currentTimeMillis()+".jpg",95);Uri uri=saveBitmap(aura,"AURA_"+safeMode()+"_"+System.currentTimeMillis()+".jpg",100);int score=score(aura);Bitmap thumb=Bitmap.createScaledBitmap(aura,180,135,true);Bitmap show=Bitmap.createScaledBitmap(aura,Math.min(aura.getWidth(),1200),(int)(aura.getHeight()*Math.min(aura.getWidth(),1200)/(float)aura.getWidth()),true);runOnUiThread(()->{lastThumb.setImageBitmap(thumb);showReview(show,score,uri);});if(aura!=oriented)aura.recycle();if(oriented!=dec)oriented.recycle();dec.recycle();}catch(Exception e){runOnUiThread(()->toast("Salvare: "+e.getMessage()));}finally{image.close();}}\n'''
new_proc = '''    private void processJpeg(Image image){\n        try{\n            ByteBuffer bb=image.getPlanes()[0].getBuffer();byte[] data=new byte[bb.remaining()];bb.get(data);\n            Bitmap dec=BitmapFactory.decodeByteArray(data,0,data.length);if(dec==null)throw new Exception("JPEG invalid");\n            Bitmap oriented=orient(dec);if(oriented!=dec)dec.recycle();\n            if(burstActive){\n                synchronized(burstFrames){burstFrames.add(oriented);if(burstFrames.size()>=burstExpected)finishComputationalBurst();}\n            }else{finishSingleFrame(oriented);}\n        }catch(Exception e){burstActive=false;runOnUiThread(()->toast("Salvare: "+e.getMessage()));}\n        finally{image.close();}\n    }\n\n    private void finishSingleFrame(Bitmap oriented)throws Exception{\n        Bitmap tone=ComputationalEngine.localToneMap(oriented,mode.equals("Noapte"));\n        Bitmap aura=applyLook(tone);if(saveOriginal)saveBitmap(oriented,"AURA_ORIGINAL_"+System.currentTimeMillis()+".jpg",95);\n        Uri uri=saveBitmap(aura,"AURA_"+safeMode()+"_"+System.currentTimeMillis()+".jpg",100);presentResult(aura,uri);\n        if(aura!=tone)aura.recycle();if(tone!=oriented)tone.recycle();oriented.recycle();\n    }\n\n    private void finishComputationalBurst(){\n        final List<Bitmap> frames=new ArrayList<>(burstFrames);burstFrames.clear();burstActive=false;\n        try{\n            int best=ComputationalEngine.bestFrameIndex(frames);Bitmap reference=frames.get(best<0?frames.size()/2:best);\n            if(saveOriginal)saveBitmap(reference,"AURA_ORIGINAL_"+System.currentTimeMillis()+".jpg",95);\n            Bitmap fused=ComputationalEngine.fuse(frames,burstNight);Bitmap aura=applyLook(fused);\n            Uri uri=saveBitmap(aura,(burstNight?"AURA_NIGHT_":"AURA_HDR_")+safeMode()+"_"+System.currentTimeMillis()+".jpg",100);\n            presentResult(aura,uri);\n            if(aura!=fused)aura.recycle();if(fused!=null)fused.recycle();\n        }catch(Exception e){runOnUiThread(()->toast("AURA fusion: "+e.getMessage()));}\n        finally{for(Bitmap b:frames)if(b!=null&&!b.isRecycled())b.recycle();updatePreview();}\n    }\n\n    private void presentResult(Bitmap aura,Uri uri){\n        int sc=score(aura);Bitmap thumb=Bitmap.createScaledBitmap(aura,180,135,true);int sw=Math.min(aura.getWidth(),1200);Bitmap show=Bitmap.createScaledBitmap(aura,sw,(int)(aura.getHeight()*sw/(float)aura.getWidth()),true);\n        runOnUiThread(()->{lastThumb.setImageBitmap(thumb);showReview(show,sc,uri);});\n    }\n'''
if old_proc not in s:
    raise SystemExit('processJpeg anchor not found')
s=s.replace(old_proc,new_proc,1)

old_analysis='''frameLum=(float)(sum/n);frameContrast=(float)Math.sqrt(Math.max(0,sum2/n-frameLum*frameLum));highlightPct=hi/(float)n;shadowPct=sh/(float)n;overlay.setHighlightMask(mask,w,h,highlightPct>.04f);classifyScene();autoEv=computeAutoEv();sceneText.setText("SCENĂ: "+scene+" · LUX "+(lux<0?"—":String.format(Locale.US,"%.0f",lux)));autoText.setText(String.format(Locale.US,"AURA AUTO · EV %+.1f · highlights %.0f%% · umbre %.0f%%",autoEv*.3f,highlightPct*100,shadowPct*100));updatePreview();updateGuide();'''
new_analysis='''frameLum=(float)(sum/n);frameContrast=(float)Math.sqrt(Math.max(0,sum2/n-frameLum*frameLum));highlightPct=hi/(float)n;shadowPct=sh/(float)n;overlay.setHighlightMask(mask,w,h,highlightPct>.04f);classifyScene();autoEv=computeAutoEv();liveAuraScore=Math.max(0,Math.min(100,(int)(100-Math.abs(frameLum-.50f)*45-highlightPct*120-shadowPct*28-Math.min(18,motion*4)-Math.min(12,Math.abs(roll)*1.2f))));sceneText.setText("SCENĂ: "+scene+" · LUX "+(lux<0?"—":String.format(Locale.US,"%.0f",lux))+" · LIVE "+liveAuraScore+"/100");autoText.setText(String.format(Locale.US,"AURA AUTO · EV %+.1f · highlights %.0f%% · umbre %.0f%%",autoEv*.3f,highlightPct*100,shadowPct*100));updatePreview();updateGuide();'''
if old_analysis not in s:
    raise SystemExit('analysis anchor not found')
s=s.replace(old_analysis,new_analysis,1)

s=s.replace('TextView h=tv("AURA PRO · v3.3",16,Color.WHITE);','TextView h=tv("AURA PRO · v4.0 MAX",16,Color.WHITE);',1)
s=s.replace('private void startBg(){if(bgThread==null){bgThread=new HandlerThread("aura-v33");','private void startBg(){if(bgThread==null){bgThread=new HandlerThread("aura-v40-max");',1)

p.write_text(s,encoding='utf-8')
print('AURA MAX Stage 1 patch applied')
