package ro.auracamera.app;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.hardware.*;
import android.hardware.camera2.*;
import android.hardware.camera2.params.Face;
import android.hardware.camera2.params.StreamConfigurationMap;
import android.media.*;
import android.net.Uri;
import android.os.*;
import android.provider.MediaStore;
import android.speech.tts.TextToSpeech;
import android.util.Range;
import android.util.Size;
import android.view.*;
import android.widget.*;

import java.io.OutputStream;
import java.nio.ByteBuffer;
import java.util.*;

public class AuraActivity extends Activity implements SensorEventListener {
    private static final int GREEN=Color.rgb(55,238,125), BLUE=Color.rgb(59,130,246), DARK=Color.rgb(4,10,16), PANEL=Color.rgb(15,24,35);
    private FrameLayout previewFrame; private TextureView preview; private SmartOverlay overlay; private ImageView lastThumb;
    private TextView modeTitle, sceneText, guideText, autoText, angleText;
    private CameraDevice camera; private CameraCaptureSession session; private CaptureRequest.Builder previewBuilder;
    private ImageReader jpegReader, rawReader; private CameraCharacteristics chars; private String cameraId; private Rect activeArray;
    private HandlerThread bgThread; private Handler bg; private boolean front=false, flash=false, grid=true, auto=true, saveOriginal=true, voice=false, rawEnabled=false;
    private int timerSeconds=0, sensorOrientation=90, autoEv=0; private float zoom=1f;
    private String mode="Mașină"; private Face[] faces=new Face[0]; private Integer lastIso; private Long lastExposureNs;

    private SensorManager sm; private final Map<Integer,Sensor> sensors=new HashMap<>();
    private float lux=-1, azimuth=0,pitch=0,roll=0,motion=0,lastPitch=0,lastRoll=0; private boolean haveOrientation=false,carCalibrated=false; private float carRefAzimuth=0;
    private float frameLum=.5f, highlightPct=0, shadowPct=0, frameContrast=.25f; private String scene="AUTO"; private boolean guideGood=false;
    private long lastAnalysis=0,lastVoice=0; private TextToSpeech tts;
    private Image pendingRaw; private TotalCaptureResult pendingRawResult;

    @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.BLACK);getWindow().setNavigationBarColor(Color.BLACK);initSensors();initTts();buildUi();}
    private int dp(int v){return (int)(v*getResources().getDisplayMetrics().density+.5f);} private TextView tv(String s,float sp,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(c);return t;}
    private GradientDrawable round(int color,int r,int stroke,int sw){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(r));if(sw>0)g.setStroke(dp(sw),stroke);return g;}

    private void initSensors(){sm=(SensorManager)getSystemService(SENSOR_SERVICE);int[] types={Sensor.TYPE_LIGHT,Sensor.TYPE_ACCELEROMETER,Sensor.TYPE_GYROSCOPE,Sensor.TYPE_ROTATION_VECTOR,Sensor.TYPE_GRAVITY,Sensor.TYPE_LINEAR_ACCELERATION,Sensor.TYPE_MAGNETIC_FIELD};for(int t:types){Sensor s=sm.getDefaultSensor(t);if(s!=null)sensors.put(t,s);}}
    private void initTts(){tts=new TextToSpeech(this,status->{if(status==TextToSpeech.SUCCESS)tts.setLanguage(new Locale("ro","RO"));});}

    private void buildUi(){
        LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(DARK);
        LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);top.setPadding(dp(12),dp(7),dp(12),dp(7));
        LogoView logo=new LogoView(this);top.addView(logo,new LinearLayout.LayoutParams(dp(42),dp(42)));
        LinearLayout brand=new LinearLayout(this);brand.setOrientation(LinearLayout.VERTICAL);brand.setPadding(dp(8),0,0,0);TextView b=tv("AURA Camera",20,Color.WHITE);b.setTypeface(Typeface.DEFAULT_BOLD);brand.addView(b);brand.addView(tv("AUTO inteligent · senzori + analiză live",10,0xFF9DB0C4));top.addView(brand,new LinearLayout.LayoutParams(0,dp(46),1));
        TextView f=icon("⚡");f.setOnClickListener(v->{flash=!flash;f.setTextColor(flash?GREEN:Color.WHITE);updatePreview();});top.addView(f);TextView sw=icon("↻");sw.setOnClickListener(v->switchCamera());top.addView(sw);TextView st=icon("⚙");st.setOnClickListener(v->showSettings(st));top.addView(st);root.addView(top,new LinearLayout.LayoutParams(-1,dp(62)));

        previewFrame=new FrameLayout(this);preview=new TextureView(this);previewFrame.addView(preview,new FrameLayout.LayoutParams(-1,-1));overlay=new SmartOverlay(this);previewFrame.addView(overlay,new FrameLayout.LayoutParams(-1,-1));
        LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(12),dp(9),dp(12),dp(9));card.setBackground(round(0xD0111924,14,0x556B7C90,1));modeTitle=tv("MAȘINĂ",16,Color.WHITE);modeTitle.setTypeface(Typeface.DEFAULT_BOLD);sceneText=tv("SCENĂ: AUTO",11,0xFFB7C5D5);guideText=tv("Calibrează fața mașinii pentru ghid 30–45°",12,Color.WHITE);autoText=tv("AURA AUTO · analiză lumină + highlights + umbre + mișcare",10,GREEN);card.addView(modeTitle);card.addView(sceneText);card.addView(guideText);card.addView(autoText);card.setOnClickListener(v->{if(mode.equals("Mașină")&&haveOrientation){carRefAzimuth=azimuth;carCalibrated=true;haptic();updateGuide();toast("Calibrare 0° realizată");}});FrameLayout.LayoutParams cp=new FrameLayout.LayoutParams(-1,-2,Gravity.TOP);cp.setMargins(dp(12),dp(12),dp(12),0);previewFrame.addView(card,cp);
        angleText=tv("📐 CAL",13,GREEN);angleText.setGravity(Gravity.CENTER);angleText.setTypeface(Typeface.DEFAULT_BOLD);angleText.setBackground(round(0xD00B151E,12,GREEN,1));FrameLayout.LayoutParams ap=new FrameLayout.LayoutParams(dp(94),dp(40),Gravity.END|Gravity.CENTER_VERTICAL);ap.setMargins(0,0,dp(12),0);previewFrame.addView(angleText,ap);
        root.addView(previewFrame,new LinearLayout.LayoutParams(-1,0,1));

        LinearLayout modes=new LinearLayout(this);modes.setGravity(Gravity.CENTER);String[] names={"Mașină","Selfie","Portret","Noapte","TikTok"};for(int i=0;i<names.length;i++){final String n=names[i];LinearLayout m=new LinearLayout(this);m.setOrientation(LinearLayout.VERTICAL);m.setGravity(Gravity.CENTER);ModeIconView iv=new ModeIconView(this,i+1);iv.setTag("icon");m.addView(iv,new LinearLayout.LayoutParams(dp(34),dp(34)));TextView lab=tv(n,10,0xFFD0D7E0);lab.setTag("label");lab.setGravity(Gravity.CENTER);m.addView(lab,new LinearLayout.LayoutParams(-1,dp(24)));m.setTag(n);m.setOnClickListener(v->selectMode(n));modes.addView(m,new LinearLayout.LayoutParams(0,dp(68),1));}
        root.addView(modes,new LinearLayout.LayoutParams(-1,dp(72)));this.modeBar=modes;
        LinearLayout quality=new LinearLayout(this);quality.setPadding(dp(14),0,dp(14),0);TextView q=tv("AUTO",11,GREEN);q.setTypeface(Typeface.DEFAULT_BOLD);quality.addView(q,new LinearLayout.LayoutParams(dp(55),dp(28)));TextView info=tv("Histogramă · Zebra · Level · Stabilitate · AURA SCORE",11,0xFFAEBBCB);info.setGravity(Gravity.END);quality.addView(info,new LinearLayout.LayoutParams(0,dp(28),1));root.addView(quality,new LinearLayout.LayoutParams(-1,dp(30)));
        FrameLayout controls=new FrameLayout(this);controls.setPadding(dp(18),dp(4),dp(18),dp(8));lastThumb=new ImageView(this);lastThumb.setScaleType(ImageView.ScaleType.CENTER_CROP);lastThumb.setBackground(round(PANEL,12,0x667A8795,1));controls.addView(lastThumb,new FrameLayout.LayoutParams(dp(58),dp(58),Gravity.CENTER_VERTICAL|Gravity.START));ShutterView sh=new ShutterView(this);sh.setOnClickListener(v->triggerPhoto());controls.addView(sh,new FrameLayout.LayoutParams(dp(82),dp(82),Gravity.CENTER));TextView pro=tv("PRO",12,Color.WHITE);pro.setGravity(Gravity.CENTER);pro.setTypeface(Typeface.DEFAULT_BOLD);pro.setBackground(round(PANEL,14,0x667A8795,1));pro.setOnClickListener(v->showSettings(pro));controls.addView(pro,new FrameLayout.LayoutParams(dp(58),dp(58),Gravity.CENTER_VERTICAL|Gravity.END));root.addView(controls,new LinearLayout.LayoutParams(-1,dp(94)));
        setContentView(root);selectMode("Mașină");preview.setSurfaceTextureListener(new TextureView.SurfaceTextureListener(){public void onSurfaceTextureAvailable(SurfaceTexture s,int w,int h){startCamera();startFrameAnalyzer();}public void onSurfaceTextureSizeChanged(SurfaceTexture s,int w,int h){}public boolean onSurfaceTextureDestroyed(SurfaceTexture s){closeCamera();return true;}public void onSurfaceTextureUpdated(SurfaceTexture s){}});
    }
    private LinearLayout modeBar;
    private TextView icon(String s){TextView v=tv(s,21,Color.WHITE);v.setGravity(Gravity.CENTER);v.setBackground(round(PANEL,12,0x667A8795,1));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(dp(42),dp(42));p.setMargins(dp(5),0,0,0);v.setLayoutParams(p);return v;}
    private void selectMode(String n){mode=n;carCalibrated=false;for(int i=0;i<modeBar.getChildCount();i++){LinearLayout m=(LinearLayout)modeBar.getChildAt(i);boolean sel=n.equals(m.getTag());m.setBackground(sel?round(0x331E6EFF,13,BLUE,2):null);((ModeIconView)m.getChildAt(0)).selected=sel;m.getChildAt(0).invalidate();((TextView)m.getChildAt(1)).setTextColor(sel?Color.WHITE:0xFFD0D7E0);}modeTitle.setText(n.toUpperCase(new Locale("ro")));if(n.equals("Selfie")&&!front)switchCamera();else if(!n.equals("Selfie")&&front)switchCamera();updateGuide();}

    private void showSettings(View anchor){LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.VERTICAL);p.setPadding(dp(16),dp(12),dp(16),dp(12));p.setBackground(round(0xFC0C1420,18,BLUE,1));TextView h=tv("AURA PRO · v3.3",16,Color.WHITE);h.setTypeface(Typeface.DEFAULT_BOLD);p.addView(h,new LinearLayout.LayoutParams(-1,dp(38)));
        Switch a=toggle("AUTO inteligent",auto);a.setOnCheckedChangeListener((b,c)->{auto=c;updatePreview();});p.addView(a);Switch g=toggle("Grilă 3×3",grid);g.setOnCheckedChangeListener((b,c)->{grid=c;overlay.grid=c;overlay.invalidate();});p.addView(g);Switch o=toggle("Salvează original + AURA",saveOriginal);o.setOnCheckedChangeListener((b,c)->saveOriginal=c);p.addView(o);Switch vo=toggle("Ghidare vocală",voice);vo.setOnCheckedChangeListener((b,c)->voice=c);p.addView(vo);Switch rw=toggle("RAW/DNG când este suportat",rawEnabled);rw.setEnabled(rawReader!=null);rw.setOnCheckedChangeListener((b,c)->rawEnabled=c&&rawReader!=null);p.addView(rw);
        TextView tim=tv("Timer: "+timerSeconds+"s · atinge pentru 0/3/10",13,Color.WHITE);tim.setPadding(0,dp(10),0,dp(10));tim.setOnClickListener(v->{timerSeconds=timerSeconds==0?3:timerSeconds==3?10:0;tim.setText("Timer: "+timerSeconds+"s · atinge pentru 0/3/10");});p.addView(tim);p.addView(tv("Senzori activi: lumină, rotație, accelerație, giroscop, gravitație, accelerație liniară, magnetometru (dacă există).",11,0xFFB6C3D2));PopupWindow w=new PopupWindow(p,dp(335),-2,true);w.setOutsideTouchable(true);w.setElevation(dp(12));w.showAtLocation(anchor,Gravity.TOP|Gravity.END,dp(8),dp(68));}
    private Switch toggle(String s,boolean c){Switch v=new Switch(this);v.setText(s);v.setTextColor(Color.WHITE);v.setChecked(c);return v;}

    private void startBg(){if(bgThread==null){bgThread=new HandlerThread("aura-v33");bgThread.start();bg=new Handler(bgThread.getLooper());}}
    private void stopBg(){if(bgThread!=null){bgThread.quitSafely();bgThread=null;bg=null;}}
    private void startCamera(){if(checkSelfPermission(Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.CAMERA},7);return;}startBg();try{CameraManager cm=(CameraManager)getSystemService(CAMERA_SERVICE);cameraId=null;for(String id:cm.getCameraIdList()){CameraCharacteristics c=cm.getCameraCharacteristics(id);Integer f=c.get(CameraCharacteristics.LENS_FACING);if(f!=null&&((front&&f==CameraCharacteristics.LENS_FACING_FRONT)||(!front&&f==CameraCharacteristics.LENS_FACING_BACK))){cameraId=id;chars=c;activeArray=c.get(CameraCharacteristics.SENSOR_INFO_ACTIVE_ARRAY_SIZE);Integer so=c.get(CameraCharacteristics.SENSOR_ORIENTATION);sensorOrientation=so==null?90:so;break;}}if(cameraId==null){toast("Camera indisponibilă");return;}Size js=maxJpeg(chars);jpegReader=ImageReader.newInstance(js.getWidth(),js.getHeight(),ImageFormat.JPEG,2);jpegReader.setOnImageAvailableListener(r->{Image im=r.acquireLatestImage();if(im!=null)processJpeg(im);},bg);setupRaw(chars);cm.openCamera(cameraId,new CameraDevice.StateCallback(){public void onOpened(CameraDevice c){camera=c;createSession();}public void onDisconnected(CameraDevice c){c.close();camera=null;}public void onError(CameraDevice c,int e){c.close();camera=null;toast("Eroare cameră "+e);}},bg);}catch(Exception e){toast("Cameră: "+e.getMessage());}}
    private Size maxJpeg(CameraCharacteristics c){StreamConfigurationMap m=c.get(CameraCharacteristics.SCALER_STREAM_CONFIGURATION_MAP);Size[] a=m==null?null:m.getOutputSizes(ImageFormat.JPEG);if(a==null||a.length==0)return new Size(4032,3024);Arrays.sort(a,(x,y)->Long.compare((long)y.getWidth()*y.getHeight(),(long)x.getWidth()*x.getHeight()));return a[0];}
    private boolean hasCapability(int cap){int[] a=chars.get(CameraCharacteristics.REQUEST_AVAILABLE_CAPABILITIES);if(a!=null)for(int x:a)if(x==cap)return true;return false;}
    private void setupRaw(CameraCharacteristics c){try{if(!hasCapability(CameraCharacteristics.REQUEST_AVAILABLE_CAPABILITIES_RAW))return;StreamConfigurationMap m=c.get(CameraCharacteristics.SCALER_STREAM_CONFIGURATION_MAP);Size[] a=m.getOutputSizes(ImageFormat.RAW_SENSOR);if(a==null||a.length==0)return;Arrays.sort(a,(x,y)->Long.compare((long)y.getWidth()*y.getHeight(),(long)x.getWidth()*x.getHeight()));Size s=a[0];rawReader=ImageReader.newInstance(s.getWidth(),s.getHeight(),ImageFormat.RAW_SENSOR,2);rawReader.setOnImageAvailableListener(r->{Image im=r.acquireLatestImage();if(im!=null){synchronized(this){if(pendingRaw!=null)pendingRaw.close();pendingRaw=im;trySaveRaw();}}},bg);}catch(Exception ignored){rawReader=null;rawEnabled=false;}}
    private void createSession(){try{SurfaceTexture st=preview.getSurfaceTexture();st.setDefaultBufferSize(1920,1080);Surface ps=new Surface(st);previewBuilder=camera.createCaptureRequest(CameraDevice.TEMPLATE_PREVIEW);previewBuilder.addTarget(ps);List<Surface> out=new ArrayList<>();out.add(ps);out.add(jpegReader.getSurface());if(rawReader!=null)out.add(rawReader.getSurface());camera.createCaptureSession(out,new CameraCaptureSession.StateCallback(){public void onConfigured(CameraCaptureSession s){session=s;updatePreview();}public void onConfigureFailed(CameraCaptureSession s){toast("Configurare eșuată");}},bg);}catch(Exception e){toast("Preview: "+e.getMessage());}}
    private void closeCamera(){try{if(session!=null)session.close();}catch(Exception ignored){}session=null;try{if(camera!=null)camera.close();}catch(Exception ignored){}camera=null;try{if(jpegReader!=null)jpegReader.close();}catch(Exception ignored){}jpegReader=null;try{if(rawReader!=null)rawReader.close();}catch(Exception ignored){}rawReader=null;}
    private void switchCamera(){front=!front;closeCamera();startCamera();}

    private boolean has(int[] a,int v){if(a==null)return false;for(int x:a)if(x==v)return true;return false;} private int clampEv(int e){Range<Integer> r=chars==null?null:chars.get(CameraCharacteristics.CONTROL_AE_COMPENSATION_RANGE);return r==null?0:Math.max(r.getLower(),Math.min(r.getUpper(),e));}
    private void applyQuality(CaptureRequest.Builder b,boolean still){try{b.set(CaptureRequest.CONTROL_MODE,CameraMetadata.CONTROL_MODE_AUTO);b.set(CaptureRequest.CONTROL_AF_MODE,CaptureRequest.CONTROL_AF_MODE_CONTINUOUS_PICTURE);b.set(CaptureRequest.CONTROL_AWB_MODE,CaptureRequest.CONTROL_AWB_MODE_AUTO);b.set(CaptureRequest.CONTROL_AE_EXPOSURE_COMPENSATION,clampEv(auto?autoEv:0));b.set(CaptureRequest.CONTROL_AE_MODE,flash&&!front?CaptureRequest.CONTROL_AE_MODE_ON_AUTO_FLASH:CaptureRequest.CONTROL_AE_MODE_ON);int[] nr=chars.get(CameraCharacteristics.NOISE_REDUCTION_AVAILABLE_NOISE_REDUCTION_MODES);if(has(nr,CaptureRequest.NOISE_REDUCTION_MODE_HIGH_QUALITY))b.set(CaptureRequest.NOISE_REDUCTION_MODE,CaptureRequest.NOISE_REDUCTION_MODE_HIGH_QUALITY);int[] ed=chars.get(CameraCharacteristics.EDGE_AVAILABLE_EDGE_MODES);if(has(ed,CaptureRequest.EDGE_MODE_HIGH_QUALITY))b.set(CaptureRequest.EDGE_MODE,CaptureRequest.EDGE_MODE_HIGH_QUALITY);int[] tm=chars.get(CameraCharacteristics.TONEMAP_AVAILABLE_TONE_MAP_MODES);if(has(tm,CaptureRequest.TONEMAP_MODE_HIGH_QUALITY))b.set(CaptureRequest.TONEMAP_MODE,CaptureRequest.TONEMAP_MODE_HIGH_QUALITY);Integer stab=chars.get(CameraCharacteristics.CONTROL_MAX_REGIONS_AF);if(still)b.set(CaptureRequest.JPEG_QUALITY,(byte)100);}catch(Exception ignored){}}
    private final CameraCaptureSession.CaptureCallback liveCb=new CameraCaptureSession.CaptureCallback(){@Override public void onCaptureCompleted(CameraCaptureSession s,CaptureRequest r,TotalCaptureResult res){Face[] f=res.get(CaptureResult.STATISTICS_FACES);faces=f==null?new Face[0]:f;lastIso=res.get(CaptureResult.SENSOR_SENSITIVITY);lastExposureNs=res.get(CaptureResult.SENSOR_EXPOSURE_TIME);runOnUiThread(()->{overlay.setFaces(faces,activeArray,front);updateGuide();});}};
    private void updatePreview(){if(previewBuilder==null||session==null)return;try{applyQuality(previewBuilder,false);session.setRepeatingRequest(previewBuilder.build(),liveCb,bg);}catch(Exception ignored){}}

    private int desiredRotation(){int r=getWindowManager().getDefaultDisplay().getRotation();int d=r==Surface.ROTATION_90?90:r==Surface.ROTATION_180?180:r==Surface.ROTATION_270?270:0;return front?(sensorOrientation+d)%360:(sensorOrientation-d+360)%360;}
    private void triggerPhoto(){if(timerSeconds==0){takePhoto();return;}final int[] n={timerSeconds};TextView c=tv(""+n[0],58,Color.WHITE);c.setGravity(Gravity.CENTER);c.setBackgroundColor(0x66000000);previewFrame.addView(c,new FrameLayout.LayoutParams(-1,-1));Handler h=new Handler(getMainLooper());Runnable rr=new Runnable(){public void run(){if(--n[0]<=0){previewFrame.removeView(c);takePhoto();}else{c.setText(""+n[0]);h.postDelayed(this,1000);}}};h.postDelayed(rr,1000);}
    private void takePhoto(){if(camera==null||session==null)return;if(motion>3.2f){guideText.setText("Ține telefonul stabil…");new Handler(getMainLooper()).postDelayed(this::takePhoto,180);return;}try{CaptureRequest.Builder b=camera.createCaptureRequest(CameraDevice.TEMPLATE_STILL_CAPTURE);b.addTarget(jpegReader.getSurface());if(rawEnabled&&rawReader!=null)b.addTarget(rawReader.getSurface());applyQuality(b,true);b.set(CaptureRequest.JPEG_ORIENTATION,0);session.capture(b.build(),new CameraCaptureSession.CaptureCallback(){@Override public void onCaptureCompleted(CameraCaptureSession s,CaptureRequest r,TotalCaptureResult res){synchronized(AuraActivity.this){pendingRawResult=res;trySaveRaw();}updatePreview();}},bg);}catch(Exception e){toast("Fotografie: "+e.getMessage());}}

    private Bitmap orient(Bitmap src){int deg=desiredRotation();Matrix m=new Matrix();if(deg!=0)m.postRotate(deg);if(front)m.postScale(-1,1);return (deg==0&&!front)?src:Bitmap.createBitmap(src,0,0,src.getWidth(),src.getHeight(),m,true);}
    private void processJpeg(Image image){try{ByteBuffer bb=image.getPlanes()[0].getBuffer();byte[] data=new byte[bb.remaining()];bb.get(data);Bitmap dec=BitmapFactory.decodeByteArray(data,0,data.length);if(dec==null)throw new Exception("JPEG invalid");Bitmap oriented=orient(dec);Bitmap aura=applyLook(oriented);if(saveOriginal)saveBitmap(oriented,"AURA_ORIGINAL_"+System.currentTimeMillis()+".jpg",95);Uri uri=saveBitmap(aura,"AURA_"+safeMode()+"_"+System.currentTimeMillis()+".jpg",100);int score=score(aura);Bitmap thumb=Bitmap.createScaledBitmap(aura,180,135,true);Bitmap show=Bitmap.createScaledBitmap(aura,Math.min(aura.getWidth(),1200),(int)(aura.getHeight()*Math.min(aura.getWidth(),1200)/(float)aura.getWidth()),true);runOnUiThread(()->{lastThumb.setImageBitmap(thumb);showReview(show,score,uri);});if(aura!=oriented)aura.recycle();if(oriented!=dec)oriented.recycle();dec.recycle();}catch(Exception e){runOnUiThread(()->toast("Salvare: "+e.getMessage()));}finally{image.close();}}
    private String safeMode(){return mode.toUpperCase(new Locale("ro")).replace('Ș','S').replace('Ă','A');}
    private Uri saveBitmap(Bitmap b,String name,int q)throws Exception{ContentValues v=new ContentValues();v.put(MediaStore.Images.Media.DISPLAY_NAME,name);v.put(MediaStore.Images.Media.MIME_TYPE,"image/jpeg");if(Build.VERSION.SDK_INT>=29)v.put(MediaStore.Images.Media.RELATIVE_PATH,"Pictures/AURA Camera");Uri u=getContentResolver().insert(MediaStore.Images.Media.EXTERNAL_CONTENT_URI,v);if(u==null)throw new Exception("MediaStore");try(OutputStream os=getContentResolver().openOutputStream(u)){b.compress(Bitmap.CompressFormat.JPEG,q,os);}return u;}
    private Bitmap applyLook(Bitmap s){float sat=1f,con=1f,br=0;if(mode.equals("Mașină")){sat=1.025f;con=1.045f;br=highlightPct>.08f?-4:0;}else if(mode.equals("Selfie")){sat=1.015f;con=1.015f;br=2;}else if(mode.equals("Portret")){sat=.995f;con=1.035f;br=1;}else if(mode.equals("Noapte")){sat=1.02f;con=1.02f;br=shadowPct>.35f?5:2;}else {sat=1.06f;con=1.04f;br=1;}Bitmap o=Bitmap.createBitmap(s.getWidth(),s.getHeight(),Bitmap.Config.ARGB_8888);Canvas c=new Canvas(o);Paint p=new Paint(Paint.ANTI_ALIAS_FLAG|Paint.FILTER_BITMAP_FLAG);ColorMatrix m=new ColorMatrix();m.setSaturation(sat);m.postConcat(new ColorMatrix(new float[]{con,0,0,0,br,0,con,0,0,br,0,0,con,0,br,0,0,0,1,0}));p.setColorFilter(new ColorMatrixColorFilter(m));c.drawBitmap(s,0,0,p);return o;}

    private synchronized void trySaveRaw(){if(pendingRaw==null||pendingRawResult==null||chars==null)return;Image im=pendingRaw;TotalCaptureResult res=pendingRawResult;pendingRaw=null;pendingRawResult=null;try{ContentValues v=new ContentValues();v.put(MediaStore.Images.Media.DISPLAY_NAME,"AURA_RAW_"+System.currentTimeMillis()+".dng");v.put(MediaStore.Images.Media.MIME_TYPE,"image/x-adobe-dng");if(Build.VERSION.SDK_INT>=29)v.put(MediaStore.Images.Media.RELATIVE_PATH,"Pictures/AURA Camera");Uri u=getContentResolver().insert(MediaStore.Images.Media.EXTERNAL_CONTENT_URI,v);if(u!=null)try(OutputStream os=getContentResolver().openOutputStream(u);DngCreator d=new DngCreator(chars,res)){d.writeImage(os,im);}}catch(Exception ignored){}finally{im.close();}}

    private void startFrameAnalyzer(){new Handler(getMainLooper()).post(new Runnable(){public void run(){if(preview!=null&&preview.isAvailable()&&System.currentTimeMillis()-lastAnalysis>650){lastAnalysis=System.currentTimeMillis();Bitmap b=preview.getBitmap(96,72);if(b!=null){analyzeFrame(b);b.recycle();}}if(preview!=null)preview.postDelayed(this,350);}});}
    private void analyzeFrame(Bitmap b){int w=b.getWidth(),h=b.getHeight(),n=w*h;double sum=0,sum2=0;int hi=0,sh=0;boolean[] mask=new boolean[n];for(int y=0;y<h;y++)for(int x=0;x<w;x++){int c=b.getPixel(x,y);float l=(.2126f*Color.red(c)+.7152f*Color.green(c)+.0722f*Color.blue(c))/255f;sum+=l;sum2+=l*l;if(l>.94f){hi++;mask[y*w+x]=true;}if(l<.08f)sh++;}frameLum=(float)(sum/n);frameContrast=(float)Math.sqrt(Math.max(0,sum2/n-frameLum*frameLum));highlightPct=hi/(float)n;shadowPct=sh/(float)n;overlay.setHighlightMask(mask,w,h,highlightPct>.04f);classifyScene();autoEv=computeAutoEv();sceneText.setText("SCENĂ: "+scene+" · LUX "+(lux<0?"—":String.format(Locale.US,"%.0f",lux)));autoText.setText(String.format(Locale.US,"AURA AUTO · EV %+.1f · highlights %.0f%% · umbre %.0f%%",autoEv*.3f,highlightPct*100,shadowPct*100));updatePreview();updateGuide();}
    private void classifyScene(){if(lux>=0&&lux<15||frameLum<.20f)scene="NOAPTE";else if(highlightPct>.08f&&frameContrast>.28f)scene="SOARE PUTERNIC";else if(lux>25000)scene="SOARE";else if(frameLum<.38f&&lux>=0&&lux<1200)scene="ÎNNORAT / UMBRĂ";else if(frameLum>.60f&&frameContrast<.20f)scene="LUMINĂ DIFUZĂ";else scene="ECHILIBRATĂ";}
    private int computeAutoEv(){if(!auto)return 0;if(highlightPct>.10f||frameLum>.72f)return -2;if(highlightPct>.04f||frameLum>.62f)return -1;if(frameLum<.25f&&shadowPct>.25f)return 2;if(frameLum<.38f)return 1;return 0;}

    private float wrap(float d){while(d>180)d-=360;while(d<-180)d+=360;return d;} private RectF face(){if(faces==null||faces.length==0||activeArray==null)return null;Face z=faces[0];for(Face f:faces)if(f.getBounds().width()*f.getBounds().height()>z.getBounds().width()*z.getBounds().height())z=f;Rect r=z.getBounds();float l=(r.left-activeArray.left)/(float)activeArray.width(),t=(r.top-activeArray.top)/(float)activeArray.height(),rr=(r.right-activeArray.left)/(float)activeArray.width(),bb=(r.bottom-activeArray.top)/(float)activeArray.height();if(front){float nl=1-rr,nr=1-l;l=nl;rr=nr;}return new RectF(l,t,rr,bb);}
    private void updateGuide(){if(guideText==null)return;String msg;boolean good=false;if(Math.abs(roll)>5){msg=roll>0?"Îndreaptă telefonul spre stânga":"Îndreaptă telefonul spre dreapta";}else if(motion>2.6f){msg="Ține telefonul stabil";}else if(mode.equals("Mașină")){if(!carCalibrated){msg="Țintește drept fața mașinii și atinge panoul pentru calibrare";angleText.setText("📐 CAL");}else{float d=wrap(azimuth-carRefAzimuth),a=Math.abs(d);angleText.setText(String.format(Locale.US,"📐 %.0f°",a));overlay.carAngle=a;overlay.carCal=true;if(pitch>18)msg="Mai jos · spre nivelul farurilor";else if(pitch<-18)msg="Mai sus · spre nivelul farurilor";else if(a<30)msg=d>=0?"Mai la dreapta · caută 30–45°":"Mai la stânga · caută 30–45°";else if(a>45)msg=d>=0?"Puțin la stânga · revino spre 35°":"Puțin la dreapta · revino spre 35°";else if(Math.abs(a-35)<=2){msg="UNGHI IDEAL · 35°";good=true;}else{msg="UNGHI RECOMANDAT · apropie de 35°";good=true;}}}else if(mode.equals("Noapte")){long ms=lastExposureNs==null?0:lastExposureNs/1000000;int iso=lastIso==null?0:lastIso;if(ms>33||iso>1200)msg="Sprijină telefonul sau caută mai multă lumină";else{msg="CADRU DE NOAPTE OPTIM";good=true;}angleText.setText("☾ AUTO");}else{RectF f=face();if(f==null)msg=mode.equals("TikTok")?"Încadrează subiectul vertical":"Încadrează fața în ghid";else if(f.centerX()<.42f)msg="Mai la stânga";else if(f.centerX()>.58f)msg="Mai la dreapta";else if(f.centerY()<.30f)msg="Mai sus";else if(f.centerY()>.58f)msg="Mai jos";else if(f.width()<.20f)msg="Apropie-te";else if(f.width()>.56f)msg="Depărtează-te";else{msg=mode.equals("Selfie")?"POZIȚIE IDEALĂ":mode.equals("Portret")?"PORTRET IDEAL":"CADRU TIKTOK IDEAL";good=true;}angleText.setText(good?"✓ IDEAL":"◎ GHID");}guideGood=good;guideText.setText(msg);guideText.setTextColor(good?GREEN:Color.WHITE);overlay.good=good;overlay.levelRoll=roll;overlay.invalidate();if(good){haptic();speak(msg);}}
    private void haptic(){try{Vibrator v=(Vibrator)getSystemService(VIBRATOR_SERVICE);if(v!=null&&v.hasVibrator()){if(Build.VERSION.SDK_INT>=26)v.vibrate(VibrationEffect.createOneShot(22,80));else v.vibrate(22);}}catch(Exception ignored){}}
    private void speak(String s){if(!voice||tts==null||System.currentTimeMillis()-lastVoice<2500)return;lastVoice=System.currentTimeMillis();tts.speak(s,TextToSpeech.QUEUE_FLUSH,null,"aura-guide");}

    private int score(Bitmap b){int w=Math.min(240,b.getWidth()),h=Math.max(1,(int)(b.getHeight()*w/(float)b.getWidth()));Bitmap s=Bitmap.createScaledBitmap(b,w,h,true);double sum=0,edge=0;int n=w*h,hi=0;for(int y=0;y<h;y++)for(int x=0;x<w;x++){int c=s.getPixel(x,y);double l=(.2126*Color.red(c)+.7152*Color.green(c)+.0722*Color.blue(c))/255.;sum+=l;if(l>.95)hi++;if(x>0){int p=s.getPixel(x-1,y);double lp=(.2126*Color.red(p)+.7152*Color.green(p)+.0722*Color.blue(p))/255.;edge+=Math.abs(l-lp);}}double lum=sum/n,sharp=edge/n;int sc=100;sc-=Math.min(22,(int)(Math.abs(lum-.50)*55));sc-=Math.min(18,(int)(hi*100.0/n));if(sharp<.045)sc-=14;if(motion>2.5)sc-=10;if(guideGood)sc+=5;s.recycle();return Math.max(0,Math.min(100,sc));}
    private void showReview(Bitmap b,int score,Uri uri){Dialog d=new Dialog(this,android.R.style.Theme_Black_NoTitleBar_Fullscreen);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setBackgroundColor(Color.BLACK);TextView h=tv("AURA SCORE  "+score+"/100",20,score>=90?GREEN:Color.WHITE);h.setGravity(Gravity.CENTER);h.setTypeface(Typeface.DEFAULT_BOLD);h.setPadding(0,dp(12),0,dp(8));r.addView(h,new LinearLayout.LayoutParams(-1,dp(58)));ImageView im=new ImageView(this);im.setImageBitmap(b);im.setScaleType(ImageView.ScaleType.FIT_CENTER);r.addView(im,new LinearLayout.LayoutParams(-1,0,1));LinearLayout buttons=new LinearLayout(this);buttons.setGravity(Gravity.CENTER);Button keep=new Button(this);keep.setText("PĂSTREAZĂ");Button redo=new Button(this);redo.setText("REFĂ");Button gal=new Button(this);gal.setText("GALERIE");buttons.addView(keep,new LinearLayout.LayoutParams(0,dp(58),1));buttons.addView(redo,new LinearLayout.LayoutParams(0,dp(58),1));buttons.addView(gal,new LinearLayout.LayoutParams(0,dp(58),1));r.addView(buttons);keep.setOnClickListener(v->d.dismiss());redo.setOnClickListener(v->d.dismiss());gal.setOnClickListener(v->{try{Intent i=new Intent(Intent.ACTION_VIEW);i.setDataAndType(uri,"image/jpeg");i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(i);}catch(Exception ignored){}d.dismiss();});d.setContentView(r);d.setOnDismissListener(x->{if(!b.isRecycled())b.recycle();});d.show();}

    @Override public void onSensorChanged(SensorEvent e){int t=e.sensor.getType();if(t==Sensor.TYPE_LIGHT){lux=e.values[0];return;}if(t==Sensor.TYPE_ROTATION_VECTOR){float[] R=new float[9],o=new float[3];SensorManager.getRotationMatrixFromVector(R,e.values);SensorManager.getOrientation(R,o);float a=(float)Math.toDegrees(o[0]),p=(float)Math.toDegrees(o[1]),r=(float)Math.toDegrees(o[2]);if(haveOrientation){float d=Math.abs(p-lastPitch)+Math.abs(r-lastRoll);motion=motion*.85f+d*.15f;}azimuth=a;pitch=p;roll=r;lastPitch=p;lastRoll=r;haveOrientation=true;updateGuide();}else if(t==Sensor.TYPE_GYROSCOPE||t==Sensor.TYPE_LINEAR_ACCELERATION){float m=(float)Math.sqrt(e.values[0]*e.values[0]+e.values[1]*e.values[1]+e.values[2]*e.values[2]);motion=motion*.9f+m*.1f;}}
    @Override public void onAccuracyChanged(Sensor s,int a){}
    @Override protected void onResume(){super.onResume();for(Sensor s:sensors.values())sm.registerListener(this,s,SensorManager.SENSOR_DELAY_GAME);if(preview!=null&&preview.isAvailable()){startCamera();startFrameAnalyzer();}}
    @Override protected void onPause(){super.onPause();sm.unregisterListener(this);closeCamera();stopBg();}
    @Override protected void onDestroy(){super.onDestroy();if(tts!=null)tts.shutdown();}
    @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==7&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED)startCamera();}
    private void toast(String s){runOnUiThread(()->Toast.makeText(this,s,Toast.LENGTH_SHORT).show());}

    static class LogoView extends View{Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);LogoView(Context c){super(c);}protected void onDraw(Canvas c){float w=getWidth(),h=getHeight(),rr=Math.min(w,h)*.40f;p.setStyle(Paint.Style.FILL);p.setColor(0xFF0B1522);c.drawRoundRect(new RectF(1,1,w-1,h-1),w*.22f,w*.22f,p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(w*.055f);p.setColor(0xFF7D4CFF);c.drawCircle(w/2,h/2,rr,p);p.setColor(0xFF27C7FF);c.drawArc(new RectF(w/2-rr,h/2-rr,w/2+rr,h/2+rr),-70,150,false,p);p.setStyle(Paint.Style.FILL);p.setColor(Color.WHITE);p.setTextAlign(Paint.Align.CENTER);p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(w*.52f);c.drawText("A",w/2,h*.69f,p);}}
    static class ShutterView extends View{Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);ShutterView(Context c){super(c);setClickable(true);}protected void onDraw(Canvas c){float x=getWidth()/2f,y=getHeight()/2f,r=Math.min(x,y)-3;p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(5);p.setColor(Color.WHITE);c.drawCircle(x,y,r,p);p.setStrokeWidth(2);p.setColor(GREEN);c.drawCircle(x,y,r-8,p);p.setStyle(Paint.Style.FILL);p.setColor(0xFFF8FAFC);c.drawCircle(x,y,r-13,p);}}
    static class ModeIconView extends View{final int type;boolean selected;Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);ModeIconView(Context c,int t){super(c);type=t;}protected void onDraw(Canvas c){p.setColor(selected?Color.WHITE:0xFFD0D7E0);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(2.5f);p.setStrokeCap(Paint.Cap.ROUND);float w=getWidth(),h=getHeight();if(type==1){RectF b=new RectF(w*.12f,h*.44f,w*.88f,h*.72f);c.drawRoundRect(b,6,6,p);c.drawLine(w*.25f,h*.44f,w*.36f,h*.28f,p);c.drawLine(w*.36f,h*.28f,w*.66f,h*.28f,p);c.drawLine(w*.66f,h*.28f,w*.76f,h*.44f,p);c.drawCircle(w*.3f,h*.72f,w*.09f,p);c.drawCircle(w*.7f,h*.72f,w*.09f,p);}else if(type==2){c.drawCircle(w*.5f,h*.34f,w*.15f,p);c.drawArc(new RectF(w*.23f,h*.48f,w*.77f,h*.92f),205,130,false,p);}else if(type==3){c.drawRect(w*.10f,h*.10f,w*.90f,h*.90f,p);c.drawCircle(w*.5f,h*.34f,w*.14f,p);c.drawArc(new RectF(w*.25f,h*.48f,w*.75f,h*.88f),205,130,false,p);}else if(type==4){Path m=new Path();m.moveTo(w*.65f,h*.12f);m.cubicTo(w*.30f,h*.18f,w*.27f,h*.70f,w*.69f,h*.82f);m.cubicTo(w*.42f,h*.89f,w*.17f,h*.70f,w*.17f,h*.45f);m.cubicTo(w*.17f,h*.22f,w*.38f,h*.06f,w*.65f,h*.12f);c.drawPath(m,p);}else{c.drawLine(w*.55f,h*.15f,w*.55f,h*.66f,p);c.drawLine(w*.55f,h*.15f,w*.78f,h*.23f,p);c.drawCircle(w*.40f,h*.70f,w*.13f,p);c.drawCircle(w*.67f,h*.73f,w*.13f,p);}}}
    static class SmartOverlay extends View{Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);boolean grid=true,good=false,carCal=false,zebra=false;float carAngle=0,levelRoll=0;RectF faceNorm;boolean[] mask;int mw,mh;SmartOverlay(Context c){super(c);setWillNotDraw(false);}void setFaces(Face[] fs,Rect active,boolean front){if(fs==null||fs.length==0||active==null){faceNorm=null;invalidate();return;}Face z=fs[0];for(Face f:fs)if(f.getBounds().width()*f.getBounds().height()>z.getBounds().width()*z.getBounds().height())z=f;Rect r=z.getBounds();float l=(r.left-active.left)/(float)active.width(),t=(r.top-active.top)/(float)active.height(),rr=(r.right-active.left)/(float)active.width(),bb=(r.bottom-active.top)/(float)active.height();if(front){float nl=1-rr,nr=1-l;l=nl;rr=nr;}faceNorm=new RectF(l,t,rr,bb);invalidate();}void setHighlightMask(boolean[] m,int w,int h,boolean z){mask=m;mw=w;mh=h;zebra=z;invalidate();}
        protected void onDraw(Canvas c){float w=getWidth(),h=getHeight();if(grid){p.setColor(0x38FFFFFF);p.setStrokeWidth(1);for(int i=1;i<3;i++){c.drawLine(w*i/3,0,w*i/3,h,p);c.drawLine(0,h*i/3,w,h*i/3,p);}}p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(3);p.setColor(good?GREEN:0xAAFFFFFF);float cy=h*.58f;c.drawLine(w*.18f,cy-levelRoll*2,w*.82f,cy+levelRoll*2,p);c.drawCircle(w/2,cy,5,p);if(faceNorm!=null){RectF r=new RectF(faceNorm.left*w,faceNorm.top*h,faceNorm.right*w,faceNorm.bottom*h);c.drawRoundRect(r,18,18,p);}if(zebra&&mask!=null&&mw>0&&mh>0){p.setStrokeWidth(1);p.setColor(0x66FFFFFF);float sx=w/mw,sy=h/mh;for(int y=0;y<mh;y+=2)for(int x=0;x<mw;x+=2)if(mask[y*mw+x])c.drawLine(x*sx,y*sy,(x+2)*sx,(y+2)*sy,p);}p.setStyle(Paint.Style.FILL);p.setColor(0xBB000000);c.drawRect(0,h-dpStatic(42),w,h,p);p.setColor(GREEN);p.setStrokeWidth(2);for(int i=0;i<24;i++){float xx=w*i/24f;float bh=(float)(6+22*Math.abs(Math.sin(i*.55)));c.drawRect(xx,h-dpStatic(8)-bh,xx+w/30f,h-dpStatic(8),p);}if(carCal){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(5);p.setColor(GREEN);float cx=w*.84f,yy=h*.42f,r=Math.min(w,h)*.13f;c.drawArc(new RectF(cx-r,yy-r,cx+r,yy+r),-45,15,false,p);double a=Math.toRadians(-45+Math.min(60,carAngle));p.setStyle(Paint.Style.FILL);c.drawCircle((float)(cx+r*Math.cos(a)),(float)(yy+r*Math.sin(a)),7,p);}}
        private static float dpStatic(int v){return v;}
    }
}
